theme: jekyll-theme-minimal
logo: https://cdn1.iconfinder.com/data/icons/36-science-badge-pixel-perfect-outline-modern-and-/64/bioinformatics-science-education-badge-logo-512.png
title: Bioinformatics
